// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF.stashes", true);
user_pref("app.normandy.user_id", "a912e16a-0f0c-4f57-9b18-0d182012170a");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1600526726);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1600526718);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3099);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1600526714);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{94f80de8-10bf-4a6d-987c-cabb92438ad8}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1600526728117");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1600528524117");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1600526723148");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1600530323148");
user_pref("browser.search.region", "FR");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1600526719");
user_pref("browser.slowStartup.averageTime", 4223);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1600526716);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1600526718855");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "6fd3cb6bf1df422a913f5b321e833948");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0304597f-0d10-4d4c-9954-cde028de2706\",\"formautofill@mozilla.org\":\"252bbd02-7439-4239-95e9-acdbd285b306\",\"screenshots@mozilla.org\":\"41b2f576-74ff-40c9-8440-386bfee59966\",\"webcompat-reporter@mozilla.org\":\"08e2f8ad-cc72-4feb-af71-92b7e6a599fc\",\"webcompat@mozilla.org\":\"97d2387a-d4a4-4363-acc6-55abec71b58b\",\"default-theme@mozilla.org\":\"042cf918-df03-47d3-bfad-34ad257c4ab8\",\"google@search.mozilla.org\":\"69059060-bed3-4177-9ee7-496f298c56d0\",\"amazondotcom@search.mozilla.org\":\"45a01f43-4eb8-4f8b-bc9e-da0abbd2d3d5\",\"wikipedia@search.mozilla.org\":\"cce9e3ff-c90a-4bad-8577-0508b35438d6\",\"bing@search.mozilla.org\":\"c4c2072c-2516-4922-b0b7-367e62f12fde\",\"ddg@search.mozilla.org\":\"6773c4ee-be83-4fb7-850d-5a52ba5db2d7\",\"amazon@search.mozilla.org\":\"0317e893-6910-4410-b1ea-f0ed7377340b\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2ad940d3-dcaf-495b-be7f-4270e923001d");
user_pref("security.sandbox.plugin.tempDirSuffix", "d06fb32c-cf85-4ff9-98a7-aeb4ce032ca0");
user_pref("toolkit.startup.last_success", 1600526711);
user_pref("toolkit.telemetry.cachedClientID", "f7f1535a-62ff-4071-b04f-f73d81f784dd");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
